name: 'LEX TRI - Temporal Agent'
description: 'Temporal debugging, visualization, and anomaly detection with Exo integration'
inputs:
  mode:
    description: 'Operation mode: diagnostics, visualize, analyze, example, or exo-publish'
    required: false
    default: 'diagnostics'
  
  input_file:
    description: 'Path to input timeline JSON file (for visualize, analyze, or exo-publish modes)'
    required: false
  
  output_file:
    description: 'Path for output file (visualization or analysis results)'
    required: false
  
  highlight_anomalies:
    description: 'Whether to highlight anomalies in visualization'
    required: false
    default: 'true'
  
  exo_integration:
    description: 'Enable integration with Exo platform'
    required: false
    default: 'false'
  
  exo_api_key:
    description: 'API key for Exo integration'
    required: false

  exo_project:
    description: 'Exo project ID or name'
    required: false
  
  exo_timeline_name:
    description: 'Name for the timeline in Exo'
    required: false
    default: 'LEX TRI Temporal Analysis'

  exo_publish_anomalies:
    description: 'Publish detected anomalies to Exo event stream'
    required: false
    default: 'true'
    
  write_ok:
    description: "Enable guarded fix mode. When set to true, LEX TRI will apply patches and create fix PRs. Otherwise it runs diagnostics only."
    required: false
    default: "false"

outputs:
  report:
    description: "VT/TT/DT diagnostic report generated by the agent."
  
  timeline_id:
    description: "ID of the timeline created in Exo (if exo_integration is enabled)"
  
  anomaly_count:
    description: "Number of anomalies detected in the timeline"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.mode != '' && format('--mode={0}', inputs.mode) || '' }}
    - ${{ inputs.input_file != '' && format('--input={0}', inputs.input_file) || '' }}
    - ${{ inputs.output_file != '' && format('--output={0}', inputs.output_file) || '' }}
    - ${{ inputs.highlight_anomalies == 'false' && '--no-highlight' || '' }}
    - ${{ inputs.exo_integration == 'true' && '--exo-integration' || '' }}
    - ${{ inputs.exo_api_key != '' && format('--exo-api-key={0}', inputs.exo_api_key) || '' }}
    - ${{ inputs.exo_project != '' && format('--exo-project={0}', inputs.exo_project) || '' }}
    - ${{ inputs.exo_timeline_name != '' && format('--exo-timeline-name={0}', inputs.exo_timeline_name) || '' }}
    - ${{ inputs.exo_publish_anomalies == 'true' && '--exo-publish-anomalies' || '' }}
